#databasedotcom.yml
# host: login.salesforce.com        # Use test.salesforce.com for sandbox
client_secret: 1328879562793066777         # This is the Consumer Secret from Salesforce
client_id: 3MVG9A2kN3Bn17htoiDQBbvHcOCenfwqRYch0IsRSq5FnvS5784K5hPimkYD.OmCbAkxReR.Cm.4dGxrUKhRX    # This is the Consumer Key from Salesforce
# sobject_module: SFDC_Models       # See below for details on using modules
debugging: true                   # Can be useful while developing
username: mikeg250@gmail.com
password: maksym25071r9GP6dlMWMqr3ilVSAMhIa
# verify_mode: OpenSSL::SSL::VERIFY_NONE



#---------------------IMPORTANT---------------------------------
# In case you want to use SalesForce API, for example, link_to some_API_url, you have to add this access token
# to then end of url:
# "-H 'Authorization:00Di0000000KWYc!AQQAQB0XDhG7mcQIk2EAEGDPse7tdScxSTNcS9ZRHyCJjY7aKQas5JN3ohHM.I26LC9KXLUeeouGQ2pJxLd__ZBvYXWa8Lz2'"